// <auto-generated />
using System;
using DigitalEmotionDiary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigitalEmotionDiary.Migrations
{
    [DbContext(typeof(DigitalEmotionDiaryDbContext))]
    [Migration("20241218011103_UpdateSeedData")]
    partial class UpdateSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("DigitalEmotionDiary.Models.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("DiaryEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiaryEntryId");

                    b.HasIndex("UserId");

                    b.ToTable("Comment");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Content = "Congraturation! Woohoo!",
                            CreatedAt = new DateTime(2024, 12, 18, 1, 11, 2, 907, DateTimeKind.Utc).AddTicks(4769),
                            DiaryEntryId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 2L,
                            Content = "We need to fight for democracy!",
                            CreatedAt = new DateTime(2024, 12, 18, 1, 11, 2, 907, DateTimeKind.Utc).AddTicks(5471),
                            DiaryEntryId = 2L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            Content = "awwww so happy for you!",
                            CreatedAt = new DateTime(2024, 12, 18, 1, 11, 2, 907, DateTimeKind.Utc).AddTicks(5475),
                            DiaryEntryId = 2L,
                            UserId = 1L
                        });
                });

            modelBuilder.Entity("DigitalEmotionDiary.Models.DiaryEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmotionId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ImageId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmotionId");

                    b.HasIndex("UserId");

                    b.ToTable("DiaryEntry");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Content = "Han Kang, South korean writer won the Nobel Prize in Literature! I'm so proud of her",
                            CreatedAt = new DateTime(2024, 12, 18, 1, 11, 2, 899, DateTimeKind.Utc).AddTicks(4779),
                            EmotionId = 1,
                            ImageId = 1L,
                            IsPublic = true,
                            Title = "Good news",
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Content = "An idiot declared martial law today, luckly paliament overruled it in two hours, could save our democracy at the end. What a drama! ",
                            CreatedAt = new DateTime(2024, 12, 18, 1, 11, 2, 899, DateTimeKind.Utc).AddTicks(5984),
                            EmotionId = 4,
                            ImageId = 2L,
                            IsPublic = true,
                            Title = "A complete shock",
                            UserId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Content = "I adapted new cat, she's so adorable!",
                            CreatedAt = new DateTime(2024, 12, 18, 1, 11, 2, 899, DateTimeKind.Utc).AddTicks(5991),
                            EmotionId = 2,
                            ImageId = 3L,
                            IsPublic = true,
                            Title = "Maya",
                            UserId = 2L
                        },
                        new
                        {
                            Id = 4L,
                            Content = "Time to make kimchi for next year, I'm ready for the war!!",
                            CreatedAt = new DateTime(2024, 12, 18, 1, 11, 2, 899, DateTimeKind.Utc).AddTicks(5996),
                            EmotionId = 1,
                            IsPublic = true,
                            Title = "Kimchi day",
                            UserId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            Content = "It's our family's yearly trip. Getting exceited!",
                            CreatedAt = new DateTime(2024, 12, 18, 1, 11, 2, 899, DateTimeKind.Utc).AddTicks(6000),
                            EmotionId = 1,
                            IsPublic = true,
                            Title = "Trip to Jeju",
                            UserId = 1L
                        },
                        new
                        {
                            Id = 6L,
                            Content = "It's awful to get sick while I'm traveling.",
                            CreatedAt = new DateTime(2024, 12, 18, 1, 11, 2, 899, DateTimeKind.Utc).AddTicks(6004),
                            EmotionId = 7,
                            IsPublic = false,
                            Title = "Sickness",
                            UserId = 2L
                        },
                        new
                        {
                            Id = 7L,
                            Content = "We live only once in our life. Let's party today! yay!",
                            CreatedAt = new DateTime(2024, 12, 18, 1, 11, 2, 899, DateTimeKind.Utc).AddTicks(6008),
                            EmotionId = 2,
                            IsPublic = true,
                            Title = "Party",
                            UserId = 2L
                        },
                        new
                        {
                            Id = 8L,
                            Content = "So exicted, I'm in the middle of shopping heaven!",
                            CreatedAt = new DateTime(2024, 12, 18, 1, 11, 2, 899, DateTimeKind.Utc).AddTicks(6012),
                            EmotionId = 2,
                            IsPublic = true,
                            Title = "Shopping",
                            UserId = 1L
                        },
                        new
                        {
                            Id = 9L,
                            Content = "So exicted, I'm in the middle of shopping heaven!",
                            CreatedAt = new DateTime(2024, 12, 18, 1, 11, 2, 899, DateTimeKind.Utc).AddTicks(6016),
                            EmotionId = 2,
                            IsPublic = true,
                            Title = "Chirstmas",
                            UserId = 1L
                        },
                        new
                        {
                            Id = 10L,
                            Content = "So exicted, I'm in the middle of shopping heaven!",
                            CreatedAt = new DateTime(2024, 12, 18, 1, 11, 2, 899, DateTimeKind.Utc).AddTicks(6020),
                            EmotionId = 2,
                            IsPublic = true,
                            Title = "Oyster",
                            UserId = 1L
                        },
                        new
                        {
                            Id = 11L,
                            Content = "Food in Riga is best in my opinion!",
                            CreatedAt = new DateTime(2024, 12, 18, 1, 11, 2, 899, DateTimeKind.Utc).AddTicks(6024),
                            EmotionId = 2,
                            IsPublic = true,
                            Title = "Riga, my home",
                            UserId = 2L
                        },
                        new
                        {
                            Id = 12L,
                            Content = "work out everyday is so important. I don't want to get sick...",
                            CreatedAt = new DateTime(2024, 12, 18, 1, 11, 2, 899, DateTimeKind.Utc).AddTicks(6028),
                            EmotionId = 8,
                            IsPublic = false,
                            Title = "Healthy life",
                            UserId = 2L
                        });
                });

            modelBuilder.Entity("DigitalEmotionDiary.Models.Emotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmotionTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmotionTypeId")
                        .IsUnique();

                    b.ToTable("Emotion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BackgroundColor = "Yellow",
                            EmotionTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            BackgroundColor = "Orange",
                            EmotionTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            BackgroundColor = "Beige",
                            EmotionTypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            BackgroundColor = "Brown",
                            EmotionTypeId = 4
                        },
                        new
                        {
                            Id = 5,
                            BackgroundColor = "Red",
                            EmotionTypeId = 5
                        },
                        new
                        {
                            Id = 6,
                            BackgroundColor = "Grey",
                            EmotionTypeId = 6
                        },
                        new
                        {
                            Id = 7,
                            BackgroundColor = "Black",
                            EmotionTypeId = 7
                        },
                        new
                        {
                            Id = 8,
                            BackgroundColor = "White",
                            EmotionTypeId = 8
                        });
                });

            modelBuilder.Entity("DigitalEmotionDiary.Models.EmotionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EmotionType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Happy"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Energized"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tired"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Anxious"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Stressed"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sad"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Annoyed"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Neutral"
                        });
                });

            modelBuilder.Entity("DigitalEmotionDiary.Models.EntryTag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DiaryEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiaryEntryId");

                    b.HasIndex("TagId");

                    b.ToTable("EntryTag");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DiaryEntryId = 1L,
                            TagId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            DiaryEntryId = 2L,
                            TagId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            DiaryEntryId = 3L,
                            TagId = 1L
                        });
                });

            modelBuilder.Entity("DigitalEmotionDiary.Models.Image", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<long>("DiaryEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiaryEntryId")
                        .IsUnique();

                    b.ToTable("Image");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "writer Han Kang",
                            DiaryEntryId = 1L,
                            Path = "./Resources/Images/hankang.webp",
                            UploadedAt = new DateTime(2024, 12, 18, 1, 11, 2, 915, DateTimeKind.Utc).AddTicks(5772)
                        },
                        new
                        {
                            Id = 2L,
                            Description = "the night under martial law",
                            DiaryEntryId = 2L,
                            Path = "./Resources/Images/120324.png",
                            UploadedAt = new DateTime(2024, 12, 18, 1, 11, 2, 915, DateTimeKind.Utc).AddTicks(6730)
                        },
                        new
                        {
                            Id = 3L,
                            Description = "maja",
                            DiaryEntryId = 3L,
                            Path = "./Resources/Images/maja.jpeg",
                            UploadedAt = new DateTime(2024, 12, 18, 1, 11, 2, 915, DateTimeKind.Utc).AddTicks(6736)
                        });
                });

            modelBuilder.Entity("DigitalEmotionDiary.Models.Like", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DiaryEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiaryEntryId");

                    b.HasIndex("UserId");

                    b.ToTable("Like");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DiaryEntryId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 2L,
                            DiaryEntryId = 2L,
                            UserId = 2L
                        });
                });

            modelBuilder.Entity("DigitalEmotionDiary.Models.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tag");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "news"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "shocking"
                        });
                });

            modelBuilder.Entity("DigitalEmotionDiary.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Email = "elin@gmail.com",
                            Password = "pass1",
                            ProfileImagePath = "elinProfile.png",
                            UserName = "Elin"
                        },
                        new
                        {
                            Id = 2L,
                            Email = "ivan@gmail.com",
                            Password = "pass2",
                            ProfileImagePath = "ivanProfile.png",
                            UserName = "Ivan"
                        });
                });

            modelBuilder.Entity("DigitalEmotionDiary.Models.Comment", b =>
                {
                    b.HasOne("DigitalEmotionDiary.Models.DiaryEntry", "DiaryEntry")
                        .WithMany("Comments")
                        .HasForeignKey("DiaryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalEmotionDiary.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DiaryEntry");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigitalEmotionDiary.Models.DiaryEntry", b =>
                {
                    b.HasOne("DigitalEmotionDiary.Models.Emotion", "Emotion")
                        .WithMany("DiaryEntries")
                        .HasForeignKey("EmotionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigitalEmotionDiary.Models.User", "User")
                        .WithMany("DiaryEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emotion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigitalEmotionDiary.Models.Emotion", b =>
                {
                    b.HasOne("DigitalEmotionDiary.Models.EmotionType", "EmotionType")
                        .WithOne("Emotion")
                        .HasForeignKey("DigitalEmotionDiary.Models.Emotion", "EmotionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmotionType");
                });

            modelBuilder.Entity("DigitalEmotionDiary.Models.EntryTag", b =>
                {
                    b.HasOne("DigitalEmotionDiary.Models.DiaryEntry", "DiaryEntry")
                        .WithMany("EntryTags")
                        .HasForeignKey("DiaryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalEmotionDiary.Models.Tag", "Tag")
                        .WithMany("EntryTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiaryEntry");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("DigitalEmotionDiary.Models.Image", b =>
                {
                    b.HasOne("DigitalEmotionDiary.Models.DiaryEntry", "DiaryEntry")
                        .WithOne("Image")
                        .HasForeignKey("DigitalEmotionDiary.Models.Image", "DiaryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiaryEntry");
                });

            modelBuilder.Entity("DigitalEmotionDiary.Models.Like", b =>
                {
                    b.HasOne("DigitalEmotionDiary.Models.DiaryEntry", "DiaryEntry")
                        .WithMany("Likes")
                        .HasForeignKey("DiaryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalEmotionDiary.Models.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiaryEntry");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigitalEmotionDiary.Models.DiaryEntry", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("EntryTags");

                    b.Navigation("Image")
                        .IsRequired();

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("DigitalEmotionDiary.Models.Emotion", b =>
                {
                    b.Navigation("DiaryEntries");
                });

            modelBuilder.Entity("DigitalEmotionDiary.Models.EmotionType", b =>
                {
                    b.Navigation("Emotion");
                });

            modelBuilder.Entity("DigitalEmotionDiary.Models.Tag", b =>
                {
                    b.Navigation("EntryTags");
                });

            modelBuilder.Entity("DigitalEmotionDiary.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("DiaryEntries");

                    b.Navigation("Likes");
                });
#pragma warning restore 612, 618
        }
    }
}
